export const Routes = {
  AppIntro: 'AppIntro',
  LoginType: 'LoginType',
  Login: 'Login',
  SignUp: 'SignUp',
  OTPVerification: 'OTPVerification',
  ForgotPassword: 'ForgotPassword',
  AuthStack: 'AuthStack',
  AppStack: 'AppStack',
  AddRequestStack: 'AddRequestStack',
  PolicyAndTerms: 'PolicyAndTerms',
  PersonalInfo: 'PersonalInfo',
  SuggestCourse: 'SuggestCourse',
  ReportIssue: 'ReportIssue',
  AlertsStack: 'AlertsStack',
};
